directories:
  scanDirectory: C:/Users/Djgeorgie/Documents/Test
  targetDirectory: C:/Users/Djgeorgie/Desktop/Moved
files:
  documents:
  - path: C:/Users/Djgeorgie/Desktop/Documents
  - extentions:
    - .doc
    - .docs
    - .pdf
    - .txt
    - .epub
  music:
  - path: C:/Users/Djgeorgie/Desktop/Music
  - extentions:
    - .mp3
    - .m4a
    - .aac
    - .wav
    - .wma
  video:
  - path: C:/Users/Djgeorgie/Desktop/Video
  - extentions:
    - .avi
    - .mpeg
    - .mpg
    - .m2ts
    - .wmv