scanDirectory: C:/Users/Djgeorgie/Documents/Test
targetPaths:
    - documents: C:/Users/Djgeorgie/Desktop/Docs
    - music: C:/Users/Djgeorgie/Desktop/Tracks
    - video: C:/Users/Djgeorgie/Desktop/video